-- require("core.plugin_config.gruvbox")
require("core.plugin_config.monokai-pro")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.Comment")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.gitsigns")
require("core.plugin_config.nvim-surround")
require("core.plugin_config.leap")
-- require("core.plugin_config.vim-illuminate")
require("core.plugin_config.nvim-neoclip")
require("core.plugin_config.cmp")

